title: AR-project @ Mandal Library and University of Oslo Library
email: Leon.Bang-Hetlevik@mandal.kommune.no
description: >- # this means to ignore newlines until "baseurl:"
  Joint augmented reality project between Mandal Library and University of Oslo Library.

url: "https://scriptotek.github.io"  # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ar-project"  # the subpath of your site, e.g. /blog
permalink: /blog/:year/:month/:day/:title.html
excerpt_separator: "<!-- more -->"

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: true

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.md
  - about.md
  - platform-evaluation.md
  - blog/index.md
  - finalized-app.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
